# Generated by Django 3.1.5 on 2021-02-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210204_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_blogimg.png', upload_to='media/post_images'),
        ),
    ]
